import './globals.css';
import { Inter } from 'next/font/google';

// components
import Navbar from '@/components/Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='pl'>
      <body className={inter.className}>
        <div
          style={{
            maxWidth: '1440px',
            marginInline: 'auto',
            padding: '1rem',
          }}
        >
          <Navbar /> {children}
        </div>
      </body>
    </html>
  );
}
